version: '{build}'
skip_tags: true
image: Visual Studio 2019
install:
build_script:
  - pwsh: ./Build.ps1
test: off
artifacts:
  - path: artifacts/Seq.App.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: n9dUtn5IAkZY8Xn4+VQ47POTNQG5G5WR1m/53LXJ0IkqNMlETq2o2cKViF7SG1WW
    skip_symbols: true
    on:
      branch: /^(main|dev)$/
  - provider: GitHub
    auth_token:
      secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
    artifact: /Seq.App.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: main
