version: '{build}'
skip_tags: true
image: Visual Studio 2019
install:
build_script:
  - pwsh: ./Build.ps1
test: off
artifacts:
  - path: artifacts/Seq.App.*.nupkg
deploy:
  - provider: NuGet
    api_key:
      secure: 90cPGBhUrjuf03moD1UWnYQV3kSOmVnsuyZALSfmq/PJ3o6pofZS2HZrC/2WmmfC
    skip_symbols: true
    on:
      branch: /^(main|dev)$/
  - provider: GitHub
    auth_token:
      secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
    artifact: /Seq.App.*\.nupkg/
    tag: v$(appveyor_build_version)
    on:
      branch: main
